---
name: Build runner

on:
  # pull_request:
    # branches:
      # - master
      # - releases/**
    # paths-ignore:
      # - "**.md"

  push:
    branches:
      - master
      - releases/**
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false # prevents workflows from running when a job fails
    timeout-minutes: 20

    strategy:
      fail-fast: true # cancel all in-progress jobs if any matrix job fails
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14

      - name: Print CI env variables
        run: |
          npx @bahmutov/print-env@v2.1.2 -e USER GITHUB || true

      - id: npm-folder
        run: |
          echo '::set-output name=dir::$(npm config get cache)'

      - name: Cache npm
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.npm-folder.outputs.dir }}
          key: ${{ runner.os }}-npm-folder-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-folder-

      - name: Cache node_modules
        uses: actions/cache@v2.1.1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}

      - id: cypress-folder
        run: |
          echo '::set-output name=dir::$(cypress cache path)'

      - name: Cache cypress
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.cypress-folder.outputs.dir }}
          # ubuntu: ~/.cache/Cypress
          # macOS: ~/Library/Caches/Cypress
          # windows: /AppData/Local/Cypress/Cache
          key: ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm i
          npx cypress cache path
          npx cypress cache list
          npx cypress verify
          npx cypress info

      - name: Run build
        env:
          CI: true
        run: |
          npm run build

      - name: Check installation
        if: ${{ runner.os == 'linux' }}
        shell: bash
        run: |
          if [ '$(git diff --ignore-space-at-eol | wc -l)' -gt '0' ]; then
            echo 'Detected uncommitted changes after build.  See status below:'
            git diff
            exit 1
          fi

      - name: Start (linux & osx)
        if: runner.os != 'windows'
        run: |
          npm run static:ci & (sleep 20 && killall -9 node)
        # or: pkill node
        # or: ps aux | grep -i node | awk '{print $2}' | xargs  kill -9)

      # - name: Start (windows)
        # if: runner.os == 'windows'
        # shell: bash
        # run: |
          # npm run static:ci & (sleep 20 && sh -c 'lsof -i :${PORT:-5000} -t' | xargs kill)
          # or: /C TASKKILL /IM node.exe /F
          # or: sh -c 'lsof -i :${PORT:-5000} -t | xargs kill
          # or: netstat -ano | findstr :5000 && taskkill /PID typeyourPIDhere /F
