name: Test action runner
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      - name: Checkout nodeJS
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Start testing
        run: npm run test
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Artifact upload screenshots
        uses: actions/upload-artifact@master
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Size images
        run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./
      - name: Artifact upload chrome screenshots
        uses: actions/upload-artifact@master
        with:
          name: screenshots-chrome
          path: cypress/screenshots/chrome
      - name: Artifact upload videos
        uses: actions/upload-artifact@master
        with:
          name: upload chrome-videos
          path: cypress/videos/chrome
      - name: Size images and videos
        run: |
          npx image-size cypress/screenshots/**/*.png
          ffprobe cypress/videos/*.mp4 || true
          mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
        working-directory: ./
