name: Cypress

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - name: Setup
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Test on nodeJS v${{ matrix.node }}
        uses: cypress-io/github-action@v2.9.7
        with:
          config-file: cypress.json
          record: true
          tag: node-${{ matrix.node }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3.0.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v3.0.0
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
