name: Cypress

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: cypress
          cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
          record: true
          parallel: true
          group: 'github_action test'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          install-command: yarn install --frozen-lockfile --silent
          # start: |
          #  yarn run build |
          #  yarn run start
          # wait-on: 'http://localhost:3000'
          command: yarn run cy:ci:chromium # default url: https://blogmops-git-main-blogmops.vercel.app
        env:
          NODE_ENV: ${{process.env.NODE_ENV}}
          CYPRESS_PROJECT_ID: ${{secrets.CYPRESS_PROJECTR_ID}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
