---
name: cypress
on:
  push:
    branches:
      - master
      - preview
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false # prevents a workflow run from failing when a job fails
    timeout-minutes: 12

    strategy:
      fail-fast: true # github will cancel all in-progress jobs if any matrix job fails
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        # machines: [1]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2.1.0
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Checkout nodeJS
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm i
          npx cypress cache path
          npx cypress cache list
          npx cypress verify
          npx cypress info

      - name: Cache global npm modules
        uses: actions/cache@v2.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache cypress
        uses: actions/cache@v2.1.0
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      - name: Cache local npm modules
        uses: actions/cache@v2.1.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.ref }}-

      - run: npm run test
        env:
          CI: true
          PORT: 5000
          NODE_ENV: production
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          TERM: xterm
          browser: chrome

      - uses: actions/upload-artifact@v2.1.2
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2.1.2
        if: failure()
        with:
          name: videos
          path: cypress/videos

      # - uses: actions/upload-artifact@v2.1.2
        # if: failure()
        # with:
          # name: screenshots
          # path: cypress/screenshots

      # - uses: actions/upload-artifact@v2.1.2
        # with:
          # name: videos
          # path: cypress/videos
