---
name: Cypress runner

on:
  pull_request:
    branches:
      - master
      - releases/**
    paths-ignore:
      - '**.md'

  # push:
    # branches:
      # - master
      # - releases/**
    # paths-ignore:
      # - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false # prevents workflows from running when a job fails
    timeout-minutes: 20

    strategy:
      fail-fast: true # cancel all in-progress jobs if any matrix job fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12

      - name: Print CI env variables
        run: npx @bahmutov/print-env@v2.1.2 -e USER GITHUB || true

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm ci

      - name: Diff changes
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          if [ '$(git diff --ignore-space-at-eol | wc -l)' -gt '0' ]; then
            echo 'Detected uncommitted changes after build.  See status below:'
            git diff
            exit 1
          fi

      - name: Verify Cypress
        run: |
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
          $(npm bin)/cypress info

      - name: Get npm cache directory
        id: cypress-cache
        run: |
          echo "::set-output name=dir::$(npx cypress cache path)"

      - name: Cache cypress
        uses: actions/cache@v2.1.1
        with:
          path: ${{ steps.cypress-cache.outputs.dir }}
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Build and export
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm run build

      - name: Run firefox tests on ${{ matrix.os }}
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run test:record:firefox
        env:
          CI: true
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          TERM: xterm

      - name: Run chrome tests on ${{ matrix.os }}
        if: startsWith(matrix.os, 'macos')
        run: npm run test:record:chrome
        env:
          CI: true
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          TERM: xterm

      - name: Run edge tests on ${{ matrix.os }}
        if: startsWith(matrix.os, 'windows')
        run: npm run test:record:edge
        env:
          CI: true
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          TERM: xterm

      - uses: actions/upload-artifact@v2.1.4
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2.1.4
        with:
          name: videos
          path: cypress/videos
