name: Test action runner
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2.1.0
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Checkout nodeJS
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Cache Cypress binary
        uses: actions/cache@v2.1.0
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-
      - run: npm run test
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - uses: actions/upload-artifact@v2.1.0
        with:
          name: screenshots
          path: cypress/screenshots
          if: failure()
      - uses: actions/upload-artifact@v2.1.0
        with:
          name: videos
          path: cypress/videos
