name: nodejs

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - production
      - main
      - fix/*
      - feature/*
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          yarn install
