name: nodejs

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: |
          yarn install
