name: WIP

on:
  push:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - production
      - main

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
